from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Farm",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("mongo_id", models.CharField(db_index=True, max_length=255, unique=True)),
                ("user_id", models.CharField(db_index=True, max_length=255)),
                ("name", models.CharField(max_length=500)),
                ("location", models.CharField(default="", max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"app_label": "core_pg"},
        ),
        migrations.CreateModel(
            name="Pond",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("mongo_id", models.CharField(db_index=True, max_length=255, unique=True)),
                ("farm_id", models.CharField(db_index=True, max_length=255)),
                ("user_id", models.CharField(db_index=True, max_length=255)),
                ("name", models.CharField(max_length=500)),
                ("size", models.FloatField(blank=True, null=True)),
                ("depth", models.FloatField(default=1.5)),
                ("pond_construction", models.CharField(default="", max_length=100)),
                ("pond_shape", models.CharField(default="", max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("active_cycle_id", models.CharField(default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"app_label": "core_pg"},
        ),
        migrations.AddIndex(
            model_name="pond",
            index=models.Index(fields=["farm_id", "is_active"], name="core_pg_pond_farm_active_idx"),
        ),
        migrations.CreateModel(
            name="Cycle",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("mongo_id", models.CharField(db_index=True, max_length=255, unique=True)),
                ("pond_id", models.CharField(db_index=True, max_length=255)),
                ("farm_id", models.CharField(db_index=True, max_length=255)),
                ("user_id", models.CharField(db_index=True, max_length=255)),
                ("name", models.CharField(default="", max_length=500)),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"app_label": "core_pg"},
        ),
        migrations.AddIndex(
            model_name="cycle",
            index=models.Index(fields=["pond_id", "is_active"], name="core_pg_cycle_pond_active_idx"),
        ),
        migrations.AddIndex(
            model_name="cycle",
            index=models.Index(fields=["farm_id", "is_active"], name="core_pg_cycle_farm_active_idx"),
        ),
        migrations.CreateModel(
            name="CycleObservation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("cycle_id", models.CharField(db_index=True, max_length=255)),
                ("pond_id", models.CharField(db_index=True, max_length=255)),
                ("farm_id", models.CharField(max_length=255)),
                ("user_id", models.CharField(max_length=255)),
                ("doc", models.IntegerField()),
                ("recorded_at", models.DateTimeField()),
                ("do_avg", models.FloatField(blank=True, null=True)),
                ("temp_avg", models.FloatField(blank=True, null=True)),
                ("nh3", models.FloatField(blank=True, null=True)),
                ("salinity", models.FloatField(blank=True, null=True)),
                ("ph", models.FloatField(blank=True, null=True)),
                ("turbidity", models.FloatField(blank=True, null=True)),
                ("abw", models.FloatField(blank=True, null=True)),
                ("biomass", models.FloatField(blank=True, null=True)),
                ("survival_rate", models.FloatField(blank=True, null=True)),
                ("sgr", models.FloatField(blank=True, null=True)),
                ("fcr", models.FloatField(blank=True, null=True)),
                ("source", models.CharField(default="manual", max_length=50)),
                ("formula_version", models.CharField(default="", max_length=50)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"app_label": "core_pg"},
        ),
        migrations.AlterUniqueTogether(
            name="cycleobservation",
            unique_together={("cycle_id", "doc")},
        ),
        migrations.AddIndex(
            model_name="cycleobservation",
            index=models.Index(fields=["cycle_id", "doc"], name="core_pg_obs_cycle_doc_idx"),
        ),
        migrations.AddIndex(
            model_name="cycleobservation",
            index=models.Index(fields=["pond_id", "recorded_at"], name="core_pg_obs_pond_date_idx"),
        ),
        migrations.CreateModel(
            name="WaterQualityReading",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("cycle_id", models.CharField(db_index=True, max_length=255)),
                ("pond_id", models.CharField(db_index=True, max_length=255)),
                ("farm_id", models.CharField(max_length=255)),
                ("user_id", models.CharField(max_length=255)),
                ("doc", models.IntegerField(blank=True, null=True)),
                ("recorded_at", models.DateTimeField(db_index=True)),
                ("parameter", models.CharField(choices=[
                    ("do", "DO"), ("temp", "Temperature"), ("nh3", "NH3"),
                    ("salinity", "Salinity"), ("ph", "pH"), ("turbidity", "Turbidity"),
                    ("co2", "CO2"), ("alkalinity", "Alkalinity"),
                ], max_length=30)),
                ("value", models.FloatField()),
                ("unit", models.CharField(default="", max_length=20)),
                ("source", models.CharField(default="manual", max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"app_label": "core_pg"},
        ),
        migrations.AddIndex(
            model_name="waterqualityreading",
            index=models.Index(fields=["cycle_id", "parameter", "recorded_at"], name="core_pg_wq_cycle_param_idx"),
        ),
        migrations.AddIndex(
            model_name="waterqualityreading",
            index=models.Index(fields=["pond_id", "recorded_at"], name="core_pg_wq_pond_date_idx"),
        ),
        migrations.CreateModel(
            name="FeedEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("cycle_id", models.CharField(db_index=True, max_length=255)),
                ("pond_id", models.CharField(max_length=255)),
                ("farm_id", models.CharField(max_length=255)),
                ("user_id", models.CharField(max_length=255)),
                ("doc", models.IntegerField()),
                ("ration_number", models.IntegerField(default=1)),
                ("feed_ration", models.FloatField(blank=True, null=True)),
                ("feed_given", models.FloatField(blank=True, null=True)),
                ("feed_leftover", models.FloatField(blank=True, null=True)),
                ("recorded_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"app_label": "core_pg"},
        ),
        migrations.AddIndex(
            model_name="feedevent",
            index=models.Index(fields=["cycle_id", "doc"], name="core_pg_feed_cycle_doc_idx"),
        ),
        migrations.CreateModel(
            name="HarvestEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("cycle_id", models.CharField(db_index=True, max_length=255)),
                ("pond_id", models.CharField(max_length=255)),
                ("farm_id", models.CharField(max_length=255)),
                ("user_id", models.CharField(max_length=255)),
                ("harvest_type", models.CharField(choices=[
                    ("partial", "Partial"), ("full", "Full"), ("emergency", "Emergency"),
                ], default="partial", max_length=20)),
                ("harvest_date", models.DateTimeField()),
                ("doc", models.IntegerField(blank=True, null=True)),
                ("weight_kg", models.FloatField(blank=True, null=True)),
                ("size_count", models.IntegerField(blank=True, null=True)),
                ("price_per_kg_idr", models.FloatField(blank=True, null=True)),
                ("revenue_idr", models.FloatField(blank=True, null=True)),
                ("notes", models.TextField(default="")),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"app_label": "core_pg"},
        ),
        migrations.AddIndex(
            model_name="harvestevent",
            index=models.Index(fields=["cycle_id", "harvest_date"], name="core_pg_harvest_cycle_date_idx"),
        ),
        migrations.CreateModel(
            name="CostEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("cycle_id", models.CharField(db_index=True, default="", max_length=255)),
                ("farm_id", models.CharField(db_index=True, max_length=255)),
                ("user_id", models.CharField(max_length=255)),
                ("category", models.CharField(choices=[
                    ("feed", "Feed"), ("seed", "Seed/PL"), ("labor", "Labor"),
                    ("chemical", "Chemical/Treatment"), ("energy", "Energy/Fuel"),
                    ("equipment", "Equipment"), ("operational", "Operational"), ("other", "Other"),
                ], default="other", max_length=30)),
                ("amount_idr", models.FloatField()),
                ("event_date", models.DateField(blank=True, null=True)),
                ("description", models.TextField(default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"app_label": "core_pg"},
        ),
        migrations.AddIndex(
            model_name="costevent",
            index=models.Index(fields=["farm_id", "cycle_id"], name="core_pg_cost_farm_cycle_idx"),
        ),
        migrations.CreateModel(
            name="FarmerNote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("user_id", models.CharField(db_index=True, max_length=255)),
                ("farm_id", models.CharField(max_length=255)),
                ("pond_id", models.CharField(default="", max_length=255)),
                ("cycle_id", models.CharField(default="", max_length=255)),
                ("content", models.TextField()),
                ("note_type", models.CharField(choices=[
                    ("text", "Text"), ("voice_transcript", "Voice Transcript"),
                    ("photo_caption", "Photo Caption"),
                ], default="text", max_length=30)),
                ("source_url", models.CharField(default="", max_length=1000)),
                ("doc", models.IntegerField(blank=True, null=True)),
                ("recorded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"app_label": "core_pg"},
        ),
        migrations.AddIndex(
            model_name="farmernote",
            index=models.Index(fields=["user_id", "farm_id", "pond_id"], name="core_pg_note_farm_pond_idx"),
        ),
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("user_id", models.CharField(db_index=True, max_length=255)),
                ("farm_id", models.CharField(max_length=255)),
                ("pond_id", models.CharField(default="", max_length=255)),
                ("cycle_id", models.CharField(default="", max_length=255)),
                ("recommendation_type", models.CharField(choices=[
                    ("feeding", "Feeding"), ("harvest", "Harvest"), ("water_quality", "Water Quality"),
                    ("cost", "Cost"), ("health", "Health/Treatment"), ("general", "General"),
                ], default="general", max_length=30)),
                ("content", models.TextField()),
                ("reasoning", models.TextField(default="")),
                ("source_refs", models.JSONField(blank=True, default=list)),
                ("confidence", models.FloatField(default=0.7)),
                ("agent_session_id", models.CharField(default="", max_length=255)),
                ("is_acknowledged", models.BooleanField(default=False)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("outcome_note", models.TextField(default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"app_label": "core_pg"},
        ),
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(fields=["user_id", "farm_id", "created_at"], name="core_pg_rec_farm_date_idx"),
        ),
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("user_id", models.CharField(db_index=True, max_length=255)),
                ("farm_id", models.CharField(default="", max_length=255)),
                ("action", models.CharField(choices=[
                    ("create", "Create"), ("update", "Update"), ("delete", "Delete"),
                ], max_length=20)),
                ("entity_type", models.CharField(max_length=50)),
                ("entity_id", models.CharField(max_length=255)),
                ("old_value", models.JSONField(blank=True, null=True)),
                ("new_value", models.JSONField(blank=True, null=True)),
                ("ip_address", models.CharField(default="", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"app_label": "core_pg"},
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(fields=["user_id", "created_at"], name="core_pg_audit_user_date_idx"),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(fields=["entity_type", "entity_id"], name="core_pg_audit_entity_idx"),
        ),
    ]
