export const servicePackageFallbacks = [
  {
    id: "farm-diagnostic",
    name: "Farm Diagnostic Review",
    slug: "farm-diagnostic-review",
    segment: "farm",
    description: "A structured second opinion for weak crop performance, mortality events, poor FCR, or failed harvest outcomes.",
    deliverables: ["60-90 minute review call", "Likely cause ranking", "Next-cycle corrective plan", "Management checklist"],
    required_data: ["Stocking and PL source", "Feed and water quality logs", "Mortality timeline", "Harvest or current biomass data"],
    price_min_idr: 3000000,
    price_max_idr: 10000000,
  },
  {
    id: "crop-planning",
    name: "Crop Planning Review",
    slug: "crop-planning-review",
    segment: "farm",
    description: "Pre-stocking review of density, feed, aeration, survival, FCR, harvest-size strategy, and economic assumptions.",
    deliverables: ["Stocking density recommendation", "Crop economics model", "Harvest-size strategy", "Risk checklist"],
    required_data: ["Pond profile", "PL source", "Cost assumptions", "Target harvest size and market price"],
    price_min_idr: 5000000,
    price_max_idr: 20000000,
  },
  {
    id: "hatchery-review",
    name: "Hatchery Performance Review",
    slug: "hatchery-performance-review",
    segment: "hatchery",
    description: "Review of broodstock handling, maturation KPIs, nauplii output, PL quality, and disease-control discipline.",
    deliverables: ["KPI review", "Operational risk map", "Corrective action priorities", "Follow-up metric plan"],
    required_data: ["Broodstock source", "Mating/spawning/hatching data", "PL quality data", "Disease test protocol"],
    price_min_idr: 10000000,
    price_max_idr: 50000000,
  },
  {
    id: "investor-dd",
    name: "Investor Technical Due Diligence",
    slug: "investor-technical-due-diligence",
    segment: "investor",
    description: "Technical risk and economics review for shrimp farm, hatchery, or integrated aquaculture investments.",
    deliverables: ["Feasibility review", "Capex/opex sanity check", "Technical risk scoring", "Go/no-go opinion"],
    required_data: ["Project plan", "Location and capacity", "Capex/opex estimates", "Management assumptions"],
    price_min_idr: 30000000,
    price_max_idr: 150000000,
  },
];

export const caseTypeByServiceSlug: Record<string, string> = {
  "farm-diagnostic-review": "farm_diagnostic",
  "crop-planning-review": "crop_planning",
  "hatchery-performance-review": "hatchery_review",
  "broodstock-pl-procurement-advisory": "procurement_advisory",
  "investor-technical-due-diligence": "investor_due_diligence",
  "monthly-advisory-retainer": "retainer",
};
