export const contentFallbacks = [
  {
    id: "farm-failure-post-mortem",
    title: "Farm Failure Post-Mortem Framework",
    slug: "farm-failure-post-mortem-framework",
    summary: "A practical structure for reconstructing crop failure timelines and ranking likely causes.",
    category: "Farm",
    tags: ["diagnostic", "mortality", "management"],
    language: "en",
    content_type: "template",
    access_level: "free",
    access_status: "free",
    body_markdown: "Use stocking, mortality, water quality, feed, disease test, treatment, and harvest data to reconstruct what changed before crop performance declined.",
  },
  {
    id: "broodstock-receiving",
    title: "Broodstock Receiving, Acclimation, and Quarantine SOP",
    slug: "broodstock-receiving-acclimation-quarantine-sop",
    summary: "Operational SOP for reducing stress and disease risk when receiving broodstock.",
    category: "Hatchery",
    tags: ["broodstock", "quarantine", "biosecurity"],
    language: "en",
    content_type: "sop",
    access_level: "paid",
    access_status: "locked",
  },
  {
    id: "harvest-economics",
    title: "Harvest Timing and Price-Size Economics",
    slug: "harvest-timing-price-size-economics",
    summary: "Decision framework for balancing DOC, size, survival, FCR, price, and cash-flow risk.",
    category: "Economics",
    tags: ["harvest", "margin", "pricing"],
    language: "en",
    content_type: "guide",
    access_level: "paid",
    access_status: "locked",
  },
];
