server {
    listen 5173;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri /index.html;
    }

    # Serve JavaScript, CSS, and other assets correctly
    location ~* \.(js|css|json|ico|png|jpg|jpeg|gif|svg|woff2|woff|ttf|otf|eot|ttf|ttc|mp4|webm|ogg|mp3|wav|flac|aac)$ {
        try_files $uri =404;
        expires max;
        access_log off;
    }

    # Handle service worker files correctly
    location /registerSW.js {
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate";
        expires off;
    }

    error_page 404 /index.html;
}