# pylint: disable=missing-class-docstring

from datetime import datetime
from mongoengine import Document, fields, QuerySetManager


class AgentConversation(Document):
    """Stores per-session conversation history for the farm assistant."""
    user_id = fields.StringField(required=True)
    session_id = fields.StringField(required=True, unique=True)
    farm_id = fields.StringField(default="")    # active context
    cycle_id = fields.StringField(default="")   # active context
    messages = fields.ListField(fields.DictField())  # {role, content, timestamp}
    created_at = fields.DateTimeField(default=datetime.now)
    last_active = fields.DateTimeField(default=datetime.now)

    meta = {
        "indexes": ["user_id", "session_id"],
        "collection": "agent_conversations",
    }
    objects = QuerySetManager()


class FarmAlert(Document):
    """Proactive alerts generated by the monitoring system."""
    user_id = fields.StringField(required=True)
    farm_id = fields.StringField(required=True)
    cycle_id = fields.StringField(required=True)
    alert_type = fields.StringField()   # "water_quality"|"growth"|"harvest_window"|"feeding"
    severity = fields.StringField()     # "info"|"warning"|"critical"
    message = fields.StringField()
    data = fields.DictField()           # raw values that triggered the alert
    is_read = fields.BooleanField(default=False)
    created_at = fields.DateTimeField(default=datetime.now)
    expires_at = fields.DateTimeField()

    meta = {
        "indexes": ["user_id", "is_read", "-created_at"],
        "collection": "farm_alerts",
    }
    objects = QuerySetManager()
